name: deploy to master
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: comando remoto
        run: |
          sshpass -p ${{ secrets.SENHA }} ssh -p 22 ${{ secrets.USUARIO }}@${{secrets.HOST}} 
          cd public_html && git pull
          
