name: deploy site
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1      
      - name: instalação do sshpass
        run: sudo apt-get install sshpass
      
      - name: entrada ssh
        run: sshpass -p '${{ secrets.PASSWORD }}' ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd public_html/ && git pull'
